name: advancevariable

on: 
  workflow_dispatch: 

jobs:
  display-context-job:
    name: "Understanding Contexts and Variables"
    runs-on: ubuntu-latest
    environment: ENV_STATUS # The name of the environment you created in Settings
    
    steps:
      - name: "1. Accessing 'vars' Context"
        # Accessing UI-defined variables
        run: |
          
          echo "Project Code:     ${{ vars.REPO_PROJECT_CODE }}"
          echo "Env Var (Custom): ${{ vars.training }}"

      - name: "2. Accessing 'secrets' Context"
        # Retrieving Org and Repo level secrets
        # Note: Secrets are masked (***) in logs for security
        run: |
          echo "Repo Secret: ${{ secrets.REPO_LEVEL_SECRET }}"
